version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto-broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto_config:/mosquitto/config

